# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba6f3085d7b1984779890d43e0d795da5192d34217fcecfb8df56e0956ff8eb3be0ace1a897c12d9dbf87f2fddf8e05e58bd09a72e5a7dcf904fc4029465dc18

test:
  secret_key_base: b068b6e3167af57873cc03d14ebc4cf736c027f27b4965f5572ee819f589fb750d799727c0c9b4d7183b8f1d2704f499e3226d24e20eafcca1eae40016c43b4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
